# Generated by Django 5.2.15 on 2026-06-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
                ('time', models.TimeField(db_index=True, verbose_name='Время')),
                ('action', models.CharField(max_length=500, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, default='', max_length=255, verbose_name='Вознаграждение')),
                ('execution_time', models.PositiveSmallIntegerField(verbose_name='Время выполнения в секундах')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('time', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HabitNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Дата напоминания')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Уведомление о привычке',
                'verbose_name_plural': 'Уведомления о привычках',
            },
        ),
    ]
