# Generated by Django 5.2.15 on 2026-06-23 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useful_habits', to='habits.habit', verbose_name='Связанная привычка'),
        ),
        migrations.AddField(
            model_name='habitnotification',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='habits.habit'),
        ),
        migrations.AddConstraint(
            model_name='habitnotification',
            constraint=models.UniqueConstraint(fields=('habit', 'scheduled_date'), name='unique_habit_notification_per_date'),
        ),
    ]
